import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="min-h-screen bg-black">
          <header className="text-white flex items-center justify-center gap-5 p-9 container">
            <Link className="text-xl font-bold text-fuchsia-600 tracking-wider hover:border-b  transition-all duration-300" href={'/'}>Home</Link>
            <Link className="text-xl font-bold text-fuchsia-600 tracking-wider hover:border-b  transition-all duration-300" href={'/blogs'}>BLogs</Link>
            <Link className="text-xl font-bold text-fuchsia-600 tracking-wider hover:border-b  transition-all duration-300" href={'/categories'}>categories</Link>
          </header>
          {children}
        </main>

      </body>
    </html>
  );
}
